config/routes.rb
Rails.application.routes.draw do
  resources :courses

  resources :students

  resources :classrooms

  root 'home#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  def student_name
    student.name
  end

  def course_name
    course.name
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  extend EnumerateIt

  has_enumeration_for :status, with: AttributeStatus

  has_many :classrooms
  has_many :students, through: :classrooms

  validates :name, presence: true
  validates :description, presence: true
  validates :status, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  extend EnumerateIt
  	
  has_enumeration_for :status, with: AttributeStatus

  has_many :classrooms
  has_many :courses, through: :classrooms

  validates :name, presence: true
  validates :register_number, presence: true
  validates :status, presence: true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json

  responders :flash

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :destroy]
	
  def index
    @classrooms = Classroom.all
  end

  def new
    @classroom = Classroom.new
  end

  def edit
  end

  def show
  end

  def create
	@classroom = Classroom.new(classroom_params)

    respond_to do |format|
	  if @classroom.save
	    format.html { redirect_to @classroom, notice: 'Matrícula realizada com sucesso.' }
	    format.json { render :show, status: :created, location: @classroom }
	  else
	    format.html { render :new }
	    format.json { render json: @classroom.errors, status: :unprocessable_entity }
	  end
	end
  end 

  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: 'Matricula foi removida.' }
      format.json { head :no_content }
    end
  end

  private

  def classroom_params
    params.require(:classroom).permit(:id, :course_id, :student_id)
  end

  def set_classroom
    @classroom = Classroom.find(params[:id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Curso criado com sucesso.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Curso editado com sucesso.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Curso removido cm sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:status, :name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Estudante criado com sucesso.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Estudante editado com sucesso.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Estudante foi removido.' }
      format.json { head :no_content }
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:id, :status, :name, :register_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Estudante" %><br>
    <%= f.collection_select(:student_id, Student.all, :id, :name, { :prompt => 'Selecione um Estudante' }) %>
  </div>
  
  <div class="field">
    <%= f.label "Curso" %><br>
    <%= f.collection_select(:course_id, Course.all, :id, :name, { :prompt => 'Selecione um Curso' }) %>
  </div>

  <div class="actions">
    <%= f.submit "Cadastrar" %>
  </div>
<% end %>

app/views/classrooms/index.html.erb
<h1>Lista de matrículas</h1>

<table>
  <thead>
    <tr>
      <th>Estudante</th>
      <th>Curso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.student_name %></td>
        <td><%= classroom.course_name %></td>
        <td><%= link_to 'Show', classroom %></td>
        <td><%= link_to 'Remover', classroom, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova matrícula', new_classroom_path %>
<%= link_to 'Home', root_path %>

app/views/classrooms/new.html.erb
<h1>Nova matrícula</h1>

<%= render 'form' %>

<%= link_to 'Voltar', classrooms_path %>

app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estudante:</strong>
  <%= @classroom.student_name %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @classroom.course_name %>
</p>


<p>
  <strong>Criada em:</strong>
  <%= @classroom.created_at %>
</p>

<%= link_to 'Voltar', classrooms_path %>
<%= link_to 'Remover', @classroom, method: :delete, data: { confirm: 'Tem certeza?' } %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(AttributeStatus.list.each, :to_s) %>    
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Cadastrar" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editar curso</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Voltar', courses_path %>

app/views/courses/index.html.erb
<h1>Lista de cursos</h1>

<table>
  <thead>
    <tr>
      <th>Estado</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.status %></td>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Editar', edit_course_path(course) %></td>
        <td><%= link_to 'Remover', course, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Curso', new_course_path %>
<%= link_to 'Home', root_path %>

app/views/courses/new.html.erb
<h1>Novo curso</h1>

<%= render 'form' %>

<%= link_to 'Voltar', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @course.status_humanize %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @course.description %>
</p>

<%= link_to 'Editar', edit_course_path(@course) %> |
<%= link_to 'Voltar', courses_path %>

app/views/home/index.html.erb
<center><h1>Sistema Escolar</h1></center>
<br><br>
<center>
	<%= link_to 'Lista de estudantes', students_path %>
	<%= link_to 'Lista de cursos', courses_path %>
	<%= link_to 'Matrículas', classrooms_path %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>School</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(AttributeStatus.list.each, :to_s) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :register_number %><br>
    <%= f.text_field :register_number %>
  </div>
  <div class="actions">
    <%= f.submit "Cadastrar"%>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editar Estudante</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Voltar', students_path %>

app/views/students/index.html.erb
<h1>Lista de Estudantes</h1>

<table>
  <thead>
    <tr>
      <th>Estado</th>
      <th>Nome</th>
      <th>Número de Registro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.status %></td>
        <td><%= student.name %></td>
        <td><%= student.register_number %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Editar', edit_student_path(student) %></td>
        <td><%= link_to 'Remover', student, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Estudante', new_student_path %>
<%= link_to 'Home', root_path %>

app/views/students/new.html.erb
<h1>Criar estudante</h1>

<%= render 'form' %>

<%= link_to 'Voltar', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @student.status_humanize %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Número de Registro:</strong>
  <%= @student.register_number %>
</p>

<%= link_to 'Editar', edit_student_path(@student) %> |
<%= link_to 'Voltar', students_path %>